<template>
  <section class="viewer">
    <div v-if="!path && synthesizedPath" class="synth">
      <header class="head">
        <h2>{{ synthesizedPath }}</h2>
      </header>
      <div class="synth-body">
        <p><strong>Synthesized at build time.</strong> This file has no source in the library — it is generated by the platform projection.</p>
        <p v-if="synthesizedNote" class="note">{{ synthesizedNote }}</p>
      </div>
    </div>
    <div v-else-if="!path" class="empty">Select a file from the tree or click a node in the graph.</div>
    <div v-else-if="pending" class="empty">Loading…</div>
    <div v-else class="content">
      <header class="head">
        <h2>{{ path }}</h2>
        <div v-if="sourceHint" class="src-hint">← {{ sourceHint }}</div>
      </header>
      <article class="body" v-html="rendered" />
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import MarkdownIt from 'markdown-it'

const props = defineProps<{
  path: string | null
  sourceHint?: string | null
  synthesizedPath?: string | null
  synthesizedNote?: string | null
}>()
const emit = defineEmits<{ (e: 'navigate', path: string): void }>()

const md = new MarkdownIt({ html: false, linkify: true, breaks: false })
const content = ref('')
const pending = ref(false)
const rendered = ref('')

async function load(p: string) {
  pending.value = true
  try {
    const res = await $fetch<{ content: string }>(`/api/file?path=${encodeURIComponent(p)}`)
    content.value = res.content
    rendered.value = renderMd(res.content)
  } catch {
    content.value = ''
    rendered.value = '<p class="err">Could not load file.</p>'
  } finally {
    pending.value = false
  }
}

function renderMd(src: string): string {
  // Split optional YAML frontmatter so we render it as a styled block, body as markdown
  let frontmatter = ''
  let body = src
  const m = src.match(/^---\n([\s\S]*?)\n---\n?/)
  if (m) {
    frontmatter = m[1]
    body = src.slice(m[0].length)
  }
  let html = md.render(body)
  // Post-process the rendered HTML so wikilinks survive markdown-it's HTML escaping
  html = html.replace(/\[\[([a-z0-9-]+)\]\]/g, (_, name) =>
    `<a href="#" data-wikilink="${name}" class="wikilink">[[${name}]]</a>`
  )
  // Also linkify YAML-style "[[name]]" inside the frontmatter block (it's already escaped to &#91;&#91;)
  const fmHtml = frontmatter
    ? `<pre class="frontmatter">${linkifyFrontmatter(escapeHtml(frontmatter))}</pre>`
    : ''
  return fmHtml + html
}

function linkifyFrontmatter(escaped: string): string {
  // Both "[[name]]" and "&quot;[[name]]&quot;" forms — match the inner name
  return escaped.replace(/\[\[([a-z0-9-]+)\]\]/g, (_, name) =>
    `<a href="#" data-wikilink="${name}" class="wikilink">[[${name}]]</a>`
  )
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!))
}

watch(() => props.path, (p) => { if (p) load(p); else { content.value = ''; rendered.value = '' } }, { immediate: true })

// Intercept wikilink clicks
function handleClick(e: MouseEvent) {
  const t = (e.target as HTMLElement).closest('a.wikilink') as HTMLElement | null
  if (!t) return
  e.preventDefault()
  const name = t.getAttribute('data-wikilink')
  if (name) emit('navigate', name)
}

import { onMounted, onBeforeUnmount } from 'vue'
onMounted(() => document.addEventListener('click', handleClick))
onBeforeUnmount(() => document.removeEventListener('click', handleClick))

const sourceHint = ref<string | null>(null)
watch(() => props.sourceHint, (v) => { sourceHint.value = v ?? null }, { immediate: true })
</script>

<style scoped>
.viewer { flex: 1; min-width: 0; overflow-y: auto; padding: var(--r-5) var(--r-6); background: var(--r-surface-2); }
.empty { color: var(--r-muted); padding: var(--r-7); text-align: center; }
.synth { color: var(--r-ink-2); max-width: 820px; }
.synth-body { line-height: 1.6; color: var(--r-ink-2); }
.synth-body strong { color: var(--r-pine); }
.synth-body .note { margin-top: var(--r-3); font-size: 12px; font-family: var(--r-mono); color: var(--r-muted); }
.head { margin-bottom: var(--r-4); padding-bottom: var(--r-3); border-bottom: 2px solid var(--r-violet); }
.head h2 { margin: 0; font-size: 14px; font-family: var(--r-mono); color: var(--r-pine); font-weight: 600; }
.src-hint { font-size: 12px; color: var(--r-muted); margin-top: 4px; font-family: var(--r-mono); }
.body { max-width: 820px; line-height: 1.6; color: var(--r-ink); }
</style>

<style>
.viewer .frontmatter {
  background: var(--r-surface);
  border: 1px solid var(--r-line);
  border-left: 3px solid var(--r-violet);
  padding: var(--r-3) var(--r-4);
  border-radius: var(--r-radius-sm);
  font-family: var(--r-mono);
  font-size: 12px;
  color: var(--r-ink-2);
  white-space: pre-wrap;
  margin-bottom: var(--r-5);
  box-shadow: var(--r-shadow-1);
}
.viewer .body h1 { font-size: 22px; margin-top: var(--r-5); color: var(--r-ink); letter-spacing: -0.01em; }
.viewer .body h2 { font-size: 18px; margin-top: 22px; color: var(--r-pine); }
.viewer .body h3 { font-size: 15px; margin-top: 18px; color: var(--r-ink-2); }
.viewer .body p { margin: 10px 0; }
.viewer .body code {
  background: var(--r-surface-3);
  padding: 2px 6px;
  border-radius: 3px;
  font-size: 12px;
  font-family: var(--r-mono);
}
.viewer .body pre {
  background: var(--r-surface);
  border: 1px solid var(--r-line);
  padding: var(--r-3);
  border-radius: var(--r-radius-sm);
  overflow-x: auto;
  font-size: 12px;
  box-shadow: var(--r-shadow-1);
}
.viewer .body pre code { background: transparent; padding: 0; }
.viewer .body a { color: var(--r-pine); text-decoration: none; font-weight: 500; }
.viewer .body a:hover { text-decoration: underline; }
.viewer .body a.wikilink {
  color: var(--r-pine-700);
  background: var(--r-violet-soft);
  padding: 1px 6px;
  border-radius: 3px;
  font-family: var(--r-mono);
  font-size: 12px;
  font-weight: 500;
}
.viewer .body a.wikilink:hover { background: var(--r-violet); text-decoration: none; }
.viewer .body ul, .viewer .body ol { padding-left: 22px; }
.viewer .body blockquote { border-left: 3px solid var(--r-violet); padding-left: var(--r-3); color: var(--r-ink-2); }
.viewer .body table { border-collapse: collapse; margin: var(--r-3) 0; background: var(--r-surface); }
.viewer .body th, .viewer .body td { border: 1px solid var(--r-line); padding: 6px 10px; }
.viewer .body th { background: var(--r-surface-3); color: var(--r-pine-700); }
</style>
